name: gym_app
description: Gym application with scheduler and training
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  chewie: ^1.3.2
  cloud_firestore: ^3.1.14
  cupertino_icons: ^1.0.4

  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  firebase_storage: ^10.2.15
  image_picker: ^0.8.5
  flutter:
    sdk: flutter

  flutter_redux: ^0.9.0
  flutter_bloc: ^7.0.1
  freezed_annotation: ^1.1.0
  flutter_local_notifications: ^9.5.2
  http: ^0.13.4
  json_annotation: ^4.5.0
  meta: ^1.7.0
  video_player: ^2.4.0
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  timezone: ^0.8.0
  permission_handler: ^9.2.0
  url_launcher: ^6.1.2
  custom_timer: ^0.0.6
  sliding_up_panel: ^2.0.0+1
  flutter_native_timezone: ^2.0.0
  percent_indicator: ^3.0.1
  dots_indicator: ^2.1.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3






dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/onboarding/onboarding.svg
    - assets/images/onboarding/onboarding_2.svg
    - assets/images/onboarding/onboarding_3.svg
    - assets/images/auth/eye_icon.png
    - assets/images/home/
    - assets/images/exercises/
    - assets/icons/home/
    - assets/icons/workouts/
    - assets/icons/social_networks/
    - assets/videos/workouts/
